name: Test

on: [pull_request]

jobs:
  go:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.16.x]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          go install github.com/magefile/mage
          mage test
  go-mod-tidy:
    name: "Go mod tidy"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Tidy check
        run: |
          go install github.com/magefile/mage
          mage gomodtidy
